# Global settings are overridden by those in a database
# server specific section
[global]
    # TDS protocol version
	tds version = 8.0
	client charset = UTF-8
    dump file = C:\FreeTDS\etc\freeTDS.log
	text size = 64512

# A typical Sybase 9.0 server
[Sybase90]
	host = localhost
	port = 2638
	tds version = 5.0
	ASA database = asademo

# A typical Microsoft server
[MSSQLTestServer]
	host = localhost
	port = 1433
	# use ntlmv2 = yes
	encryption = request
	tds version = 8.0
