[global]
        min pool conn = 5
        max pool conn = 10
        max member age = 120

[mypool]
        user = PPNUser 
        password = Admin2013
        database = tempdb
        server = MSSQLTestServer
        port = 5000